name: Sort Files Workflow

on:
  push:
    branches:
      - main

jobs:
  sort-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      - name: Sort Files
        run: |
          python sort_files.py
          
      - name: Commit Changes
        run: |
          git config --global user.name "Yu-Chueh Wang"
          git config --global user.email yuchuehw@outlook.com
          git add ./src
          git commit -m 'source folder updated!'
          git push
